# build environment
FROM node:18.9.1-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./smb-app/package.json ./
COPY ./smb-app/package-lock.json ./
COPY ./smb-app/tsconfig.json ./
RUN npm ci --force
RUN npm install react-scripts@3.4.1 -g
COPY ./smb-app/src ./src
COPY ./smb-app/public ./public
RUN npm run build

# production environment
FROM nginx:1.19.7-alpine
COPY config/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
