version: "3.3"
services:

  smb-front:
    container_name: smb-front
    build:
      context: .
      dockerfile: Dockerfile_two
      args:
        NGINX_CONF: ./config/nginx.conf
    restart: always
    ports:
      - "8078:80"
    expose: 
      - 80
    depends_on:
        - smb-api
    networks:
        - smb-net

  mysql-smb:
    container_name: mysql-smb
    image: mysql:8.0.29
    expose:
      - 3306
    ports:
      - "3300:3306"
    env_file:
      - .env 
    volumes: 
      - "./dumps:/docker-entrypoint-initdb.d"
    restart: "always"
    networks:
      - smb-net

  smb-api:
    container_name: smb-api
    restart: "always"
    env_file:
      - .env 
    environment:
      - TZ=America/Caracas
    ports:
      - "8079:8080"
    build:
        context: .
        dockerfile: Dockerfile
    expose:
        - 8080
    depends_on:
        - mysql-smb
    networks:
        - smb-net


networks:
  smb-net:
    driver: bridge