version: "3.3"
services:
  mysql-smb:
    container_name: mysql-smb
    image: mysql:8.0.29
    expose:
      - 3306
    env_file:
      - .env 
    volumes: 
      - "./dumps:/docker-entrypoint-initdb.d"
    restart: "always"

  smb-api:
    container_name: smb-api
    restart: "always"
    env_file:
      - .env 
    environment:
      - TZ=America/Caracas
    ports:
      - "8081:8080"
    build:
        context: .
        dockerfile: Dockerfile

    expose:
        - 8080
