import os

MYSQL_USER = os.getenv("USER_DB")
MYSQL_PASS = os.getenv("MYSQL_ROOT_PASSWORD")
MYSQL_NAME_HOST = "mysql-smb:3306"
MYSQL_NAME = os.getenv("MYSQL_DATABASE")
FACEBOOK_TOKEN = os.getenv("FACEBOOK_TOKEN")
INSTAGRAM_TOKEN = os.getenv("INSTAGRAM_TOKEN")
FACEBOOK_API_VERSION = os.getenv("FACEBOOK_API_VERSION")


FACEBOOK_TOKEN = "EAAHALBD7GzoBACv87DcCIXFsSvkLXfvSwTCWYqA1fvrlj4Omqg6aVbQi3iXeAZBUJWLjJbqNeyJHCDsC89WJSCO6qkn3c4BQvhiDFzyNqSz80JqXpiZBO8kBq1YbcGIlmWyjundPOks586lAk8txeoWZApWIX22wdLbopcI6IwyV4HYwXFG"
FACEBOOK_TOKEN = "EAAHALBD7GzoBAKRZCr3bVID4OfQGtEyE85qBNH4mmLuxWuqqJQBSt5jsNdH086lzgCO3ueTGykWEZAWuuDke990x5FKAiNOOZBFWMn9Wg9zi9a4fU230ehrkwvTINhcLwm7O9anxYKJ1olgVgZBtxZCy7K0sf7C5Xkk6ZARAlpunYbzJL0ZBNIiCnd0PQYG54g9OLlu39AvWgZDZD"
INSTAGRAM_TOKEN = ""
FACEBOOK_API_VERSION = "v14.0"

URL_DB = (
    f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASS}@{MYSQL_NAME_HOST}/{MYSQL_NAME}"
)


URL_DB = f"mysql+pymysql://root:password@localhost:3300/ScheduledMessage"
