import os 

MYSQL_USER=os.getenv("USER_DB")
MYSQL_PASS=os.getenv("MYSQL_ROOT_PASSWORD")
MYSQL_NAME=os.getenv("MYSQL_DATABASE")
FACEBOOK_TOKEN=os.getenv("FACEBOOK_TOKEN")
INSTAGRAM_TOKEN=os.getenv("INSTAGRAM_TOKEN")
FACEBOOK_API_VERSION=os.getenv("FACEBOOK_API_VERSION")